version: '2.0'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: todo-cache
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
  todo-api:
    image: voter-api:v2
    container_name: voter-api
    restart: always
    ports:
      - '1080:1080'
    depends_on:
      - cache